### ISSUE TITLE
`'cid' file is absent, container wasn't started correctly`

### ISSUE THREAD

**Issue by sils1297** [yegor256/rultor#1003]
In 2 of 3 cases nowadays I get this error `'cid' file is absent, container wasn't started correctly` which is really bad because I *always* have to retry the merge.

Created as per https://github.com/yegor256/rultor/issues/942#issuecomment-183460504

**Comment by yegor256** [comment]
@sils1297 can you give a few links to most recent logs please?

**Comment by AbdealiJK** [comment]
[here](https://github.com/coala-analyzer/coala/pulls?q=is%3Apr+file+is+absent%2C+container+wasn%27t+is%3Aclosed) is a list of all of them

Here's a list of the PR links:
https://github.com/coala-analyzer/coala/pull/1459
https://github.com/coala-analyzer/coala/pull/1290
https://github.com/coala-analyzer/coala/pull/1321
https://github.com/coala-analyzer/coala/pull/1214

**Comment by original-brownbear** [comment]
@sils1297 Went through the list  provided by @AbdealiJK 

The first three:
https://github.com/coala-analyzer/coala/pull/1459 
https://github.com/coala-analyzer/coala/pull/1290
https://github.com/coala-analyzer/coala/pull/1321
throw this error:
```
gpg --keyserver hkp://pool.sks-keyservers.net --verbose --recv-keys 9AF0FA4C
gpg: requesting key 9AF0FA4C from hkp server pool.sks-keyservers.net
gpgkeys: HTTP fetch error 52: Empty reply from server
gpg: no valid OpenPGP data found.
```
This is not Rultor,  but an issue with the key server you're trying to call here.
As far as I can see you're using your own docker image for this,
why not just add this step `gpg --keyserver hkp://pool.sks-keyservers.net --verbose --recv-keys 9AF0FA4C` to the Dockerfile. This should speed up your build and remove this unstable call by just having to work out once when building the Docker image.

The remaining issue https://github.com/coala-analyzer/coala/pull/1214#issuecomment-171908785
is in all likelihood the outcome of the Docker server running out of disk space.
I could also with a significantly lower likelihood be the result of instabilities in the device mapper.
As you can see in #1009, we upgraded the docker version Rultor uses from 1.8.2 to 1.10.1.
There have been a vast number of fixes to the device mapper implementation between those two releases and there is no sporadically occurring issue know in Docker raising the the exact error in that build. This in all likelihood will not come up again as a result of problems with the DM.
Potentially running out of disk space will be fixed by the incoming fix for https://github.com/yegor256/rultor/issues/942 allowing us to remove old images periodically.

Unless I missed something in the above analysis, you please close this @sils1297 ?
Thanks! :)

**Comment by sils1297** [comment]
> This is not Rultor, but an issue with the key server you're trying to call here.

I have no idea what's going on here but why should we care about keyservers when we just want to use a public docker image? Are we doing something wrong?

**Comment by sils1297** [comment]
Ah sorry that is our code? Rultor logs always confuse me.

**Comment by original-brownbear** [comment]
@sils1297 sorry, this was my bad, it appeared the gpg call came from your setup script this was not the case! There is a separate issue on our end causing this, no worries you're not doing anything wrong. I will create a separate issue for this now and link it here, 2 min :)

**Comment by sils1297** [comment]
Ah cool, then I can close https://github.com/coala-analyzer/rultor-python/issues/5 :D

**Comment by original-brownbear** [comment]
@sils1297 Opened #1015 for the remaining issue around the gpg keyserver communication error.

Given that this ticket mixes issues I think it's best to close it and continue there unless you feel I missed any of the here reported issues ? :)

**Comment by sils1297** [comment]
think you got it covered pretty well, thanks @original-brownbear !

**Comment by sils1297** [comment]
FWIW we're trying to merge a PR desperately since a day about... https://github.com/coala-analyzer/coala-quickstart/pull/1 we tried merging like ten times and always get the CID error.

**Comment by sils1297** [comment]
oh sorry that one is our problem

**Comment by sils1297** [comment]
though the error messae below our error message is confusing

**Comment by hypothesist** [comment]
We're getting the error again FWIW: https://github.com/coala-analyzer/coala-bears/pull/657#issuecomment-238760055 [[Full log]](http://www.rultor.com/t/9245-238759868)

**Comment by sils1297** [comment]
@hypothesist not rultors fault: https://github.com/coala-analyzer/coala-bears/pull/657#issuecomment-238786258
