### ISSUE TITLE
Staging in Rultor

### ISSUE THREAD

**Issue by sebing** [yegor256/rultor#1054]
Can we have a staging in rultor?

-    If a PR is accepted. It should be linked to a commit. Not just blindly take from the branch?
-    In the current implementation. After the merge request and acceptance, If a developer modify the branch, the changes are pushed to the master. I feel this is a danger.

An example of the problem:

The merge request is success for this PR(https://github.com/yegor256/takes/pull/551)
The rultor status is success(http://www.rultor.com/t/6645-184799518)
Even the deploy status is also success(http://www.rultor.com/t/6645-185839123) 
But the changes are not reflecting in Master.

**Comment by original-brownbear** [comment]
@sebing please see my comment in yegor256/takes#551 this is not Rultor imo.

**Comment by sebing** [comment]
@original-brownbear I think it is not an issue.

**Comment by sebing** [comment]
@original-brownbear Can we have a staging in rultor?
- If a PR is accepted. It should be linked to a commit. Not just blindly take from the branch?
- In the current implementation. After the merge request and acceptance, If a developer modify the branch, the changes are pushed to the master. I feel this is a danger.

**Comment by original-brownbear** [comment]
@sebing makes sense.
Could you update the issue title and description with what you just posted ? It's a valid concern, lets have a clear cut ticket on the matter.

**Comment by sebing** [comment]
@original-brownbear updated the issue.

**Comment by original-brownbear** [comment]
@sebing thanks :) Though we need to make another change here, let me explain than you can more or less copy and paste this to the ticket and I'll dispatch it :)

yegor256/taks#511 is not a valid example of the issue I see here.
Honestly this one was/is just sloppy work by 2-3 people ;)

1. Dev made an accepted fix.
2. Rultor tries to merge it but it fails because it merged some other fix before that and now ran into conflicts. => standard ... nothing we can do about that ... just need to fix the branch and merge.
3. Now Dev tries to fix the branch but makes a mistake, pushes a bad commit to the branch.
4. Neither CR nor Architect notice this and issue the merge command again!

**... nothing Rultor can do about step 4, this is fully the fault of the Architect for issuing the `merge` command again in 4.** (although I would advise the Dev to rebase against upstream master instead of merge with it next time around ;) ).

The way I see it the issue is rather this:
1. Someone issues a `merge` command.
2.There is a time span of one to at times up to ~15-20min until Rultor gets to working on it.
3. Dev can push to the branch meanwhile causing the approved PR **+ whatever the Dev pushed between 1 and 2** to be merged.

Please keep in mind that Rultor does not differentiate between say `Rultor please merge` and `Rultor try to merge again` :) All merge commands are the same pretty much as long as they have merge as the first word. 

So I think we should update this issue description to my scenario, the current example cannot be handled by Rultor ... this needs humans to be more careful ;) , makes sense ?

**Comment by sebing** [comment]
@original-brownbear Thank you for the detailed description. 

If rultor can accept a commit id to merge than a branch. I feel we have a solution to the problem. 

(My idea was, we need a staging solution. From issue raising to deployment. May be rultor may not be the right place for that)

**Comment by original-brownbear** [comment]
@sebing yea that would be out of Rultor's scope.
I suggest to close here for now then, I think we were talking about very different things :)

**Comment by sebing** [comment]
@original-brownbear closing the issue.

**Comment by original-brownbear** [comment]
@sebing forgot to close I think :)

**Comment by sebing** [comment]
@original-brownbear closing the issue. Sorry for the confusion.
