### ISSUE TITLE
Need more information to fix the Puzzle 1018-15a5404e

### ISSUE THREAD

**Issue by essobedo** [yegor256/rultor#1058]
There are couple of things unclear that prevent me to fix the issue #1053 .

1. [This part](https://github.com/yegor256/rultor/blob/master/src/test/java/com/rultor/agents/daemons/StartsDaemonITCase.java#L134-L137) of the unit test seems to be incorrect as the provided xpath doesn't match with a Talk content but more with a Profile content, Can you confirm?
2. As far as I understand from the unit test, so far we expect a warning if only if we have at least one path corresponding to `/p/entry[@key='merge']/entry[@key='script']/text()` that matches exactly with `yegor256/rultor`. So do we agree that we won't have a warning if we have entries with different value of the key attribute whose text content match also exactly with `yegor256/rultor` neither if we have `/p/entry[@key='merge']/entry[@key='script']/text()` that matches with `something yegor256/rultor` or `yegor256/rultor something` or `something yegor256/rultor something`. Can you confirm?
3. In case we trigger a warning, I guess we are supposed to let the agent execute the talk normally, the only difference will be the value of _/talk/daemon/dir/text()_ that should be "#### Deprecation Notice ####/path/to/the/dir" instead of "/path/to/the/dir", Can you confirm?
4. If my assumption in the question 3 is correct, it would mean that we will have a value of the tag _dir_ that isn't valid anymore since the corresponding XSD expects a String that matches with `[0-9a-zA-Z_\\:/+\.-]+`, so doesn't it mean that you expect a different warning prefix like _Warning:_ or am I supposed to modify the XSD file?

Thank you in advance for your answers.

**Comment by essobedo** [comment]
@alex-palevsky needed for #1053

**Comment by original-brownbear** [comment]
@essobedo Let me go one by one, thanks for writing this up :)

1. Yes sorry for missing this when reviewing the PR, you're 100% right the test is wrong. Since #1053 asks to fix the test anyhow, please handle it there.
2. Slightly confusing question, but probably the fault of what happened before. In a sense it's just this :)     ... If the image specified in the `.yml` is `yegor256` => always print the message **except for when the repo used is actually this one**. That is something to be read from the profile in this case (given that the target repo matters).
3. Yes confirmed :)
4. Not quite sure I understand this question. The functionality reading the stdOut from the build is able to read hashes as chars. Just look at any build like this one http://www.rultor.com/t/7354-190195331 and search for `#`. What am I missing here ? :)

**Comment by essobedo** [comment]
>  Not quite sure I understand this question. The functionality reading the stdOut from the build is able to read hashes as chars. Just look at any build like this one http://www.rultor.com/t/7354-190195331 and search for #. What am I missing here ? :)

Let me reformulate then, the XML format representing a Talk is defined by a XML Schema Definition aka XSD file that you can find [here](https://github.com/yegor256/rultor/blob/master/src/main/resources/com/rultor/spi/talk.xsd), if don't respect the XSD, your XML will be considered as invalid thus it will be rejected. And here according to the XSD, the _tag_ dir doesn't support a content with # as you can see [here](https://github.com/yegor256/rultor/blob/master/src/main/resources/com/rultor/spi/talk.xsd#L76-L80). So I cannot add any hash in the dir value unless I modify the XSD which is not necessary what we expect.
What you want is to have a warning in the stdOut, if it can be done in a different way, is it still acceptable to you? Or do you rely somewhere in your code on this prefix added to the value of the tag dir ?

**Comment by original-brownbear** [comment]
@essobedo sorry now I see your point you are 100% correct in your criticism.
Look at this ... https://github.com/yegor256/rultor/blob/master/src/test/java/com/rultor/agents/daemons/StartsDaemonITCase.java#L97

=> the test is incomplete here. It checks against the directory name, while it should obviously check against the content of the `stdOut` file ... like so (check the code linked to get the fully picture :) ):

```
 final ByteArrayOutputStream baos = new ByteArrayOutputStream();
  new Shell.Safe(new TalkShells(talk.read()).get()).exec(
            String.format("cat %s/stdout", dir),
            new NullInputStream(0L),
            baos, baos
        );
```
=> Please complete the test accordingly in the other ticket.

Nice job at wrapping your head around this code so quickly! :)
We can close here and continue in the other ticket then right ?

**Comment by essobedo** [comment]
@original-brownbear thx it is clear now

**Comment by essobedo** [comment]
@alex-palevsky Another question why do we need the notice in both StartsDaemon and EndsDaemon?

**Comment by essobedo** [comment]
@original-brownbear could you please answer my last question? I'm stuck otherwise, thx in advance.

**Comment by original-brownbear** [comment]
@essobedo Hey sorry had this one on low priority, you're stuck either way in that ticket as it depends on another one. See the comments there, so no worries this does not count as spending time on the ticket either way :) In fact it should also show up as having an impediment ( or 2 now ) in your agenda, so you're good in that regard.

That being said answer: we eventually simply decided to show the notice at the beginning and end of the build output. It does make some sense since the output is very long in most cases (kind of makes you scroll down without looking at some point :D), this way likely people debugging their builds will at least have seen it once :) No deeper reason for that :)

**Comment by essobedo** [comment]
@original-brownbear that's very clear now thank very much.
