### ISSUE TITLE
Cannot build rultor usng `mvn clean install -Pqulice` (unit test errors)

### ISSUE THREAD

**Issue by dpisarenko** [yegor256/rultor#687]
When I run `mvn clean install -Pqulice` on a Windows 7 machine inside the rultor directory (branch rultor-576), I get 27 test errors:

```
Results :

Tests in error:
  QnStopTest.buildsRequest:59 ExceptionInInitializer
  QnFirstOfTest.getsFirstReq:62 ExceptionInInitializer
  QnVersionTest.repliesInGithub:62 ExceptionInInitializer
  QnDeployTest.buildsRequest:63 NoClassDefFound Could not initialize class com.r
...
  QnHelloTest.repliesInGithub:60 ExceptionInInitializer
  QnAloneTest.locksRepo:68 NoClassDefFound Could not initialize class com.rultor
...
  QnStatusTest.buildsReport:78 ExceptionInInitializer
  QnConfigTest.repliesInGithub:62 ExceptionInInitializer
  QnMergeTest.buildsRequest:65 ExceptionInInitializer
  ReportsTest.reportsRequestResult:60 ExceptionInInitializer
  StartsRequestTest.startsMergeRequest:201->repo:419 ╗ IllegalState java.io.IOEx
...
  StartsRequestTest.performsStopRequest:244->exec:404 ╗ IllegalState java.io.IOE
...
  StartsRequestTest.runsAsRootIfRequested:344->repo:419 ╗ IllegalState java.io.I
...
  StartsRequestTest.runsReleaseWithDockerfile:258->repo:419 ╗ IllegalState java.
...
  StartsRequestTest.startsDeployRequest:104->repo:419 ╗ IllegalState java.io.IOE
...
  StartsRequestTest.startsReleaseRequest:168->repo:419 ╗ IllegalState java.io.IO
...
  QnIfCollaboratorTest.blocksRequest:62 ExceptionInInitializer
  QnLastOfTest.getsLastReq:62 NoClassDefFound Could not initialize class com.rul
...
  AgentsTest.processesTalk:59 ╗ NoClassDefFound Could not initialize class com.r
...
  CommentsTagTest.createsRelease:63 ExceptionInInitializer
  CommentsTagTest.duplicatesRelease:83 NoClassDefFound Could not initialize clas
...
  UnderstandsTest.ignoresLaterReq:104 NoClassDefFound Could not initialize class
...
  UnderstandsTest.understandsIssueBody:129 ExceptionInInitializer
  UnderstandsTest.understandsMessage:72 NoClassDefFound Could not initialize cla
...
  QnByArchitectTest.rejectsIfNotArchitect:67 ExceptionInInitializer
  QnReleaseTest.buildsRequest:63 ExceptionInInitializer
  QnReferredToTest.buildsRequest:63 NoClassDefFound Could not initialize class c
...

Tests run: 80, Failures: 0, Errors: 27, Skipped: 6

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 51.873 s
[INFO] Finished at: 2014-12-26T16:00:20+04:00
[INFO] Final Memory: 41M/108M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.
17:test (default-test) on project rultor: There are test failures.
[ERROR]
[ERROR] Please refer to d:\dev\teamed.io\rultor\target\surefire-reports for the
individual test results.
```
Expected result: I can build rultor using `mvn clean install -Pqulice` (including unit and code quality tests) without errors.

Please provide information on what I can do to successfully run `mvn clean install -Pqulice`.

**Comment by wentwog** [comment]
@alex-palevsky I have 2 questions.

1) the first issue behind the tests failing is 
```
Caused by: java.lang.RuntimeException: XPathFactory#newInstance() failed to create an XPathFactory for the default object model: http://java.sun.com/jaxp/xpath/dom with the XPathFactoryConfigurationException: javax.xml.xpath.XPathFactoryConfigurationException: java.util.ServiceConfigurationError: javax.xml.xpath.XPathFactory: jar:file:/C:/Users/DP118M/.m2/repository/net/sourceforge/saxon/saxon/9.1.0.8/saxon-9.1.0.8-xpath.jar!/META-INF/services/javax.xml.xpath.XPathFactory:2: Illegal configuration-file syntax
    at javax.xml.xpath.XPathFactory.newInstance(XPathFactory.java:102)
    at com.jcabi.xml.XMLDocument.<clinit>(XMLDocument.java:84)
```
and it was fixed at #654 by @yegor256 by saying we can use Java7 instead of Java8.
So, I suppose, this closes the issue?

2) after closing the 1) issue, there some more test failures. And I feel 30mins is not enough to fix the remained test failures. How should we proceed: add more time here, or I am to create another github issue and we close this one ?

**Comment by yegor256** [comment]
@wentwog as far as I understand, all tests mentioned above fail because of one root cause. Once we fix it, all of them will be fixed. If you think that there are other issues, report them as separate tickets. All other questions resolve with @dpisarenko, since he is the reporter of the ticket

**Comment by alex-palevsky** [comment]
> @alex-palevsky I have 2 questions.
> 
> 1) the first issue behind the tests failing is 
> ```
> Caused by: java.lang.RuntimeException: XPathFactory#newInstance() failed to create an XPathFactory for the default object model: http://java.sun.com/jaxp/xpath/dom with the XPathFactoryConfigurationException: javax.xml.xpath.XPathFactoryConfigurationException: java.util.ServiceConfigurationError: javax.xml.xpath.XPathFactory: jar:file:/C:/Users/DP118M/.m2/repository/net/sourceforge/saxon/saxon/9.1.0.8/saxon-9.1.0.8-xpath.jar!/META-INF/services/javax.xml.xpath.XPathFactory:2: Illegal configuration-file syntax
>     at javax.xml.xpath.XPathFactory.newInstance(XPathFactory.java:102)
>     at com.jcabi.xml.XMLDocument.<clinit>(XMLDocument.java:84)
> ```
> and it was fixed at #654 by @yegor256 by saying we can use Java7 instead of Java8.
> So, I suppose, this closes the issue?
> 
> 2) after closing the 1) issue, there some more test failures. And I feel 30mins is not enough to fix the remained test failures. How should we proceed: add more time here, or I am to create another github issue and we close this one ?

@wentwog agreed, take your time

**Comment by yegor256** [comment]
@wentwog I don't think #654 made a correct conclusion. It's not a JDK8 problem. Check this build: https://semaphoreapp.com/yegor256/rultor/branches/master/builds/85 It failed and it is Java 1.7. Here is why it failed:

    Caused by: java.lang.RuntimeException: XPathFactory#newInstance() failed to create
    an XPathFactory for the default object model: http://java.sun.com/jaxp/xpath/dom with
    the XPathFactoryConfigurationException: javax.xml.xpath.XPathFactoryConfigurationException:
    java.util.ServiceConfigurationError: javax.xml.xpath.XPathFactory:
    jar:file:/home/runner/.m2/repository/net/sourceforge/saxon/saxon/9.1.0.8/saxon-9.1.0.8-xpath.jar!/META-INF/services/javax.xml.xpath.XPathFactory:2:
    Illegal configuration-file syntax
	at javax.xml.xpath.XPathFactory.newInstance(XPathFactory.java:102)
	at org.xembly.XpathDirective.<clinit>(XpathDirective.java:62)
	... 20 more

**Comment by yegor256** [comment]
This is what we have in `saxon-9.1.0.8-xpath.jar!/META-INF/services/javax.xml.xpath.XPathFactory`:

    net.sf.saxon.xpath.XPathFactoryImpl
    http\://java.sun.com/jaxp/xpath/dom:    net.sf.saxon.xpath.XPathFactoryImpl
    http\://saxon.sf.net/jaxp/xpath/om:     net.sf.saxon.xpath.XPathFactoryImpl
    http\://www.xom.nu/jaxp/xpath/xom:      net.sf.saxon.xpath.XPathFactoryImpl
    http\://jdom.org/jaxp/xpath/jdom:       net.sf.saxon.xpath.XPathFactoryImpl
    http\://www.dom4j.org/jaxp/xpath/dom4j: net.sf.saxon.xpath.XPathFactoryImpl

**Comment by yegor256** [comment]
@wentwog I suspect that this is the problem of different JDK implementations. OpenJDK understands this format of the file, while Oracle JDK doesn't... what do you think?

**Comment by wentwog** [comment]
**The problem**
@yegor256 I think the problem is [this](https://saxonica.plan.io/issues/1944) Saxon bug.
To summarize: saxon has the new line issue in .../saxon-9.1.0.8-xpath.jar!/META-INF/services/javax.xml.xpath.XPathFactory.
This newlines are tolerated by Java6&7, but not tolerated by Java8.

**The solution**
The issue was fixed in saxon 9.5.1.5. So we can update.
But two question arise here:
1) our dependency scope of saxon artifacts is runtime - so can we update our server environment to the new version ?
2) The 9.5.1.5 is not present in public maven repositories. It's available at Saxon's [SourceForge](http://sourceforge.net/projects/saxon/files/Saxon-HE/9.5/) -  but in what repository can we place this jar ?

Having these two issues, I feel that it is easier to remain on 9.1.0.8 and bypass the corrupted services file problem by utilizing the way XPathFactory implementation [search mechanism](http://docs.oracle.com/javase/8/docs/api/javax/xml/xpath/XPathFactory.html#newInstance-java.lang.String-) works.
In practice: In tests we set "javax.xml.xpath.XPathFactory:http://java.sun.com/jaxp/xpath/dom" System property through Surefire plugin.
In production we set the same property in ${java.home}/lib/jaxp.properties.

@yegor256 what do you think ?

**Comment by yegor256** [comment]
@wentwog looks like we can't update, because 9.5.1.5 is not available in any public repos, right? I don't like the idea of hosting this artifact somewhere by ourselves.

I like your suggestion about "bypassing the corrupted file". Don't worry about production, it works perfectly fine in production. We only care about Maven build. Let's fix the issue for the build and we're done.

**Comment by wentwog** [comment]
@yegor256 ok I will do "bypassing the corrupted file".
But we need to understand that if someone will want to deploy Rultor in Java8 environment, he will need to take additional steps to configure XPathFactory implementation pickup.

**Comment by wentwog** [comment]
pull request #706

**Comment by wentwog** [comment]
@alex-palevsky  the PL is merged. Can we close the ticket ?

**Comment by yegor256** [comment]
@wentwog ask @dpisarenko to close it, it's his complaint

**Comment by wentwog** [comment]
@dpisarenko the PL is merged. Can we close the ticket ?

**Comment by dpisarenko** [comment]
@wentwog As far  as I remember, last week I was able to build rultor on Travis CI, so the issue seems to be fixed. I'll close it.

**Comment by alex-palevsky** [comment]
@wentwog Thanks a lot, I just topped your account for **30 mins**, transaction ID `49986878`

+30 added to your rating, current score is: [+65](http://www.netbout.com/b/35104?open=rating)
