### ISSUE TITLE
Building/running Rultor under Windows

### ISSUE THREAD

**Issue by maurezen** [yegor256/rultor#758]
I remember reading somewhere that the main detriment for rultor under Windows is that Docker is not available. 

Well, [not anymore](https://docs.docker.com/installation/windows/). Yes, VirtualBox is involved to a degree, but it runs.

So, I guess it would be nice to have a Windows build profile (we'll probably have to run some tests in Docker) and package!

**Comment by yegor256** [comment]
@maurezen in this case we don't need to change anything. If someone wants us to run his builds on his own Windows box, he just has to open SSH there and make sure `docker` starts.

But this is not what our users may want. The goal is not to run Docker inside Windows (it's easy), but to run Windows inside Docker (it's almost impossible, as far as I understand). The problem now is that we can't build .Net or iOS products. Because they need something that is not Linux.

So, let's wait until Docker can actually run some other operating system besides Linux :)

**Comment by maurezen** [comment]
@yegor256 If someone wants to run rultor under Windoes, he should build it first. I remember some tests in rultor build process failing under Windows because they invoke bash scripts (and hence the enforcer rule forbidding build under Windows). Shouldn't that be modified?

**Comment by yegor256** [comment]
@maurezen oh, that's another story. we're just disabling tests on Windows and that's it. in general, Windows is a platform that is not suitable for professional development, as I see it. so, there is no reason to invest too much money/time into making our builds fully supported by Windows. they should not fail, that's true, but making extra efforts to fully support Windows - it's an overkill. I can't understand why Windows is still alive, to be honest :)

**Comment by maurezen** [comment]
@yegor256 at the moment the build plainly fails due to enforcer rule. How about we remove it and just disable those tests that require linux-only components? I agree that windows may not deserve more effort, but the failure to build out of the box is just not right.

Windows being unsuited for professional development is another story, we probably shouldn't delve into argument. Let's just agree that plenty of professional developers work under Windows.

**Comment by yegor256** [comment]
@maurezen yeah, we did it here: https://github.com/yegor256/rultor/pull/724 I think we should wait until Rultor can check build stability with Appveyor (#722) and then try to enable Windows again. If we do it now, a new test will be added to the code, incompatible with Windows and someone will complain. So, for now it's better to disable Windows entirely.
