### ISSUE TITLE
squash merge

### ISSUE THREAD

**Issue by yegor256** [yegor256/rultor#782]
Let's add an option into `merge` section to [squash](http://stackoverflow.com/questions/5308816/how-to-use-git-merge-squash) branches during merge:

```
merge:
  squash: true
```

By default it's `false`.

**Comment by alxn** [comment]
Obviously the downside to this is loosing the "author" of the commit, maybe something like https://github.com/jnothman/git-squash would be useful.

Alternatively, there since git 1.7, there is `git rebase --autosquash`. This requires the developer to put `squash!` at the start of their commit message during code-review time.

**Comment by alex-palevsky** [comment]
I will find a developer for the task soon...

**Comment by alex-palevsky** [comment]
@nhekfqn the task is yuors

**Comment by alex-palevsky** [comment]
@yegor256 thanks for the ticket, your account was topped for 15 mins, payment 000-88155300

**Comment by yegor256** [comment]
seems to be working

**Comment by yegor256** [comment]
documentation is not updated

**Comment by alex-palevsky** [comment]
@yegor256 since the ticket has no milestone I set it to 2.0

**Comment by alex-palevsky** [comment]
@yegor256 thanks for the report, I topped your acc for 15 mins, payment ID `000-54cd2814`

**Comment by alxn** [comment]
@yegor256 what happened, just want a docs update?

**Comment by yegor256** [comment]
@alxn it's implemented and documented, we're done here
