### ISSUE TITLE
How to override mvn clean test?

### ISSUE THREAD

**Issue by velo** [yegor256/rultor#805]
When I run ````@rultor merge````

@rultor does run ````mvn clean test ```` ...
http://www.rultor.com/t/2767-84955006

But my code does fail on test only, how can I override this to run ````mvn install```` instead?

**Comment by yegor256** [comment]
@velo you should create `.rultor.yml` file in the root directory of your repo and configure that command there:

```yaml
merge:
  script: |
    mvn install
```

**Comment by yegor256** [comment]
More information about this `.rultor.yml` is here: http://doc.rultor.com/reference.html

**Comment by velo** [comment]
I did that!

https://github.com/velo/maven-formatter-plugin/pull/5/files

**Comment by yegor256** [comment]
@velo at the moment, rultor always uses `.rultor.yml` from master branch. So, this file is ignored, since it's in the branch which you're still planning to merge. We have a ticket about it: https://github.com/yegor256/rultor/issues/802

So, just put your `.rultor.yml` to master branch and you'll be fine

**Comment by velo** [comment]
Ow, I see, thanks!

**Comment by velo** [comment]
Would be a nice improvement tough
