### ISSUE TITLE
Stop using obsolete <xmp> tag

### ISSUE THREAD

**Issue by cvrebert** [yegor256/rultor#862]
Rultor's build log pages (e.g. http://www.rultor.com/t/4014-109171614) use the `<xmp>` tag.
This tag is obsolete. From the HTML5 spec itself:
> #### [15.2 Non-conforming features](https://html.spec.whatwg.org/multipage/obsolete.html#xmp)
> Elements in the following list are entirely obsolete, and must not be used by authors:
> [...]
> * `xmp`

[From Mozilla Developer Network](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/xmp):
> #### Obsolete
> This feature is obsolete. Although it may still work in some browsers, its use is discouraged since it could be removed at any time. Try to avoid using it.
> #### Note: Do not use this element.
> * It has been deprecated since HTML3.2 and was not implemented in a consistent way. It was completely removed from the language in HTML5.

**Comment by yegor256** [comment]
@cvrebert that's a valid problem, but there is a reason behind this tag. We can't use `<pre>` at the moment, because we would have to escape the output to make it compatible with HTML. Simply put, we will have to convert `<` to `&lt;`, etc. We can't do it now, because we're dealing with an input stream, which is a stream of bytes, not Unicode characters (1+ bytes each).

Thus, to solve this problem we should parse the input stream of bytes, convert it to an iterable of Unicode lines (instances of `String`) and then add them to `<pre>`.

**Comment by yegor256** [comment]
@cvrebert but I agree, we have to do it :) so, thanks for the bug

**Comment by alex-palevsky** [comment]
@cvrebert this task will get someone's attention soon

**Comment by alex-palevsky** [comment]
@cvrebert there is no milestone yet, so I set it to `2.0`

**Comment by yegor256** [comment]
@rultor release, tag is `1.59.5`

**Comment by yegor256** [comment]
@rultor stop

**Comment by yegor256** [comment]
@rultor release, tag is `1.59.5`

**Comment by yegor256** [comment]
@cvrebert it's fixed, please take a look and close this ticket if everything is OK
