### ISSUE TITLE
RFE: docker image: Install pip

### ISSUE THREAD

**Issue by sils** [yegor256/rultor#904]
Hey, would be nice if you could install `pip` and `pip3` on your docker image to have a better environment for python projects.

**Comment by alex-palevsky** [comment]
@yegor256 please do something about this issue

**Comment by sils1297** [comment]
FYI it doesn't matter for us as we're using an own docker image by now but it's easy to do for you and you'd make life for pythonic projects (which are many and growing) easier.

**Comment by yegor256** [comment]
@sils1297 maybe you can contribute? here is the [`Dockerfile`](https://github.com/yegor256/rultor/blob/master/src/docker/Dockerfile)

**Comment by sils1297** [comment]
Sorry, time's too short for that ATM. Feel free to close if you don't want
that, we have our own image anyway but I still thing others can profit.

**Comment by alex-palevsky** [comment]
@sils1297 I set milestone here to `2.0`, let me know if it is wrong

**Comment by original-brownbear** [comment]
@yegor256 pinging you here since you initially tagged this as a bug.

I think we should close this to be honest:
1. The author of the issue does not have the issue anymore.
2. More importantly, this is not something that Rultor should do in my opinion. The official Docker images `python:2.7.11` as well as `python:3.5.1` provide pip/pip3 just fine and in a clearly defined environment and authors can add the line making Rultor use the image to their .rultor.yml easily.
Also this introduces risks and is not necessarily all that helpful:
* Providing more than Rultor's dependencies in the official Rultor image will only help a subset of Python users anyways, namely those using the specific Python 2.x and 3.x versions we chose.
* Using this would be bad practice on the part of the projects doing so, they should run their builds in an image they control all Python (and related dependencies) versions in.
* Not so important but still: The current Rultor image is extremely large by Docker standards and takes a long time to build. We should rather work towards reducing it's size than blow it up further to avoid future surprise dependency issues.

=> unless you disagree I'd ask for this to be closed.

**Comment by original-brownbear** [comment]
@alex-palevsky this is postponed

**Comment by alex-palevsky** [comment]
> @alex-palevsky this is postponed

@original-brownbear sure, thanks, I added "postponed" label to it

**Comment by alex-palevsky** [comment]
> @alex-palevsky this is postponed

@original-brownbear I will ask somebody else to pick this up

**Comment by pnatashap** [comment]
@yegor256 this issue can be closed, as python 3 and pip are included in docker now. 
https://github.com/yegor256/rultor-image/blob/master/Dockerfile#L206

**Comment by yegor256** [comment]
@sils indeed, we have `pip` now
