### ISSUE TITLE
PR doesn't  closed by Rultor

### ISSUE THREAD

**Issue by dmzaytsev** [yegor256/rultor#918]
https://github.com/yegor256/netbout/pull/762
Rultor reports about successful merge, but the PR doesn't  closed automatically by Rultor and still in open state. What is the reason? Should I close it manually?

<hr id='w'>

**Comment by yegor256** [comment]
@dmzaytsev I don't know why it's happening, but sometimes (very rarely) I see that. Github, for some reason, doesn't close the pull request. It thinks that the merge didn't happen. I think we have to check the status of the PR from Rultor and close it.

**Comment by alex-palevsky** [comment]
@dmzaytsev we will find someone to do this task, soon

**Comment by alex-palevsky** [comment]
@dmzaytsev I set the milestone to 2.0 since there is nothing set yet

**Comment by alex-palevsky** [comment]
@dmzaytsev thanks for the report, I topped your acc for 15 mins, payment ID `63019370`

**Comment by original-brownbear** [comment]
@dmzaytsev this was now discussed in #1001, but to properly summarize it here for the person dealing with it eventually:

* This hapens when the merge involves a rebase and it would have not been possible for the merge to be fast forwarded without that rebase.
 * Put differently, this happens when the commit hashes on the branch change due to the rebase.

# Fix must include:
The agree upon solution in #1001 that needs to be implemented here specifies what needs to be done here:
* **IF** the `rebase` option is set to true, this needs to happen:
 * Rultor rebases then `--ff` merges ( already done )
 * Rultor closes the PR ( needs implementation)
 * Rultor posts a message to the ticket explaining that the PR was merged despite the closed state, but not set to "merged" as a result of the merge having needed a rebase.

**Comment by alex-palevsky** [comment]
@vkuchyn This task is yours, please go ahead keeping in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). If any questions, don't hesitate to ask right here... **30 mins** is the budget of the task. This is exactly how much will be paid when the problem is [solved](http://www.xdsd.org/2014/04/15/definition-of-done.html) (no matter how much time you will actually spend). See [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more information

**Comment by vkuchyn** [comment]
@original-brownbear 

> IF the rebase option is set to true, this needs to happen:

You mean rebase option in merge block, described in .rultor.yml? 
Can you explain what is that flag for?

**Comment by original-brownbear** [comment]
@vkuchyn check out the documentation [here](http://doc.rultor.com/reference.html) all there at the bottom in **Merge, Deploy, Release** :)

**Comment by vkuchyn** [comment]
@original-brownbear thanks.
One more question - to clarify the whole picture. After merge rultor pushes changes to github and github automatically closes PR (it's feature). But when use rebase instead merge before push - we need to close PR manually, as far as github's logic doesn't support such case. Am I correct in problem vision?

**Comment by original-brownbear** [comment]
@vkuchyn yes, spot on :)

**Comment by vkuchyn** [comment]
@original-brownbear I have a question about design and conventions. In rultor we have a chain of agents (implements interface Agent) that have method proceed that returns list of directives to modify talk. I missunderstood what is it for? When do I need to change somehow talk in my agent and when not?

**Comment by original-brownbear** [comment]
@vkuchyn You got the general idea right I think :)

> When do I need to change somehow talk in my agent and when not?

Not sure what kind of answer you are aiming at here. I mean, yes you're passing around data via the `Directives`. And yes those are used by Agents to extract data from.
So I mean you want to change those directives in case the next thing handling them needs some information passed on to it.
But I mean this task does not really require you to do any sort of tricky modification to existing functionality here, simply identify those rebase cases, then fire off logic from there that posts the answer + closes the PR. 
How you do it is, so long as you respect our coding standards and have proper tests for your fix up to you for the most part :)

**Comment by vkuchyn** [comment]
@alex-palevsky fixed in #1049 Please, find someone for review

**Comment by alex-palevsky** [comment]
> @alex-palevsky fixed in #1049 Please, find someone for review

@vkuchyn thank you!

**Comment by alex-palevsky** [comment]
@dmzaytsev once `918-89660440` puzzle is resolved (later, in another ticket), this ticket will be fully complete

**Comment by vkuchyn** [comment]
@dmzaytsev please, close this ticket - merged in #1049

**Comment by dmzaytsev** [comment]
@vkuchyn thanks

**Comment by alex-palevsky** [comment]
@vkuchyn Thank you, I have added **30 mins** to your account in payment/transaction "`80118889`", time consumed: 215 hours and 34 mins; +30 to your rating, your total score is [+150](http://www.netbout.com/b/36353?open=rating)

**Comment by alex-palevsky** [comment]
@dmzaytsev the last puzzle `918-89660440`/#1056 solved

**Comment by 0pdd** [comment]
@dmzaytsev the puzzle [#1376](https://github.com/yegor256/rultor/issues/1376) is still not solved.
