### ISSUE TITLE
rultor rejects deploy request from commander

### ISSUE THREAD

**Issue by dmzaytsev** [yegor256/rultor#947]
rultor rejects my request to deploy although I'm in commander's list in [.rultor.yml](https://github.com/yegor256/netbout/blob/master/.rultor.yml#L72)
see https://github.com/yegor256/netbout/pull/821#issuecomment-152118718

**Comment by yegor256** [comment]
@dmzaytsev it's a different problem. you're in commanders list, but for `release`, not for `deploy`. see that `.rultor.yml` you mentioned. the problem is that rultor thinks that every command must be approved by one of architects. we should make it possible to define architects per command, as this ticket suggests: #806

**Comment by dmzaytsev** [comment]
@yegor256 yep, I hadn't saw the commit https://github.com/yegor256/netbout/commit/e9c56b155be3560fb823d82cfe16ec45b7418ad7
why @karato did it?

**Comment by yegor256** [comment]
@dmzaytsev the idea is that everybody should be able to deploy, not just architects. That will be more logical, right? Deployment should be an easy and frequently repeated procedure. Anyone should be able to do this. That's why @karato removed "commanders" in all projects. But now we have a bug in rultor. Not a bug, but lack of functionality. Maybe you can fix #806? I can assign it to you.
